version: "3.8"

services: 
  inventory-api:
    container_name: inventory-api
    build: 
      context: ./InventoryApi/
    image: inventory-api:latest
    ports: 
      - "8080:80"
    networks: 
      - inventory-api
    volumes: 
      - "./Database:/app/database"

  pizza-api:
    container_name: pizza-api
    build: 
      context: ./PizzaApi/
    image: pizza-api:latest
    ports: 
      - "13337:80"
    networks: 
      - inventory-api
      
  frontend:
    container_name: frontend
    build: 
      context: ./Frontend/
    image: frontend:latest
    ports: 
      - "4200:80"
    networks: 
      - inventory-api

networks: 
  inventory-api:
    external: false